//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicInstrumentDB.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamousMusician
    {
        public int FamousMusicianId { get; set; }
        public string FullName { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public string MusicGenre { get; set; }
        public string Description { get; set; }
        public System.Guid OwnderId { get; set; }
    }
}
