//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicInstrumentDB.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentFamily
    {
        public int FamilyId { get; set; }
        public System.Guid OwnerId { get; set; }
        public string FamilyName { get; set; }
        public string Description { get; set; }
        public string Classification { get; set; }
        public string Tuning { get; set; }
    }
}
